### ISSUE TITLE
Rethink event handling and effects

### ISSUE THREAD

**Issue by fomkin** [fomkin/korolev#164]
Currently one event handler can produce only two transitions. Idea is to allow make any number of transitions. It will make Korolev application much more flexible. List of changes I plan:

1. [x] Remove `eventWithAccess`. `event` will have `access` by default.
2. [x] `access.transition(t: Transition): F[Unit]` instead of immediate/deferred transitions.
3. [x] `EventResult` deprived of links to transitions. New `EventResult` is `case class EventResult(effect: F[_], stopPropagation: Boolean)`.
4. [x] Add `access.state: F[S]` which gives current state.
5. [x] Add `access.sessionId` (which includes `deviceId` and `sessionId`).
6. [x] Add `access.valueOf`. Shortcut for access.property[String](_, _)
7. [x] Add parens to `elementId`
8. [x] Make `Transition` alias to `S => S` instead of `PartialFunction[S, S]`
9. [x] Rename `ApplicationContext` to `Context`

To Do

1. [x] Documentation
2. [x] Update g8 repository

```scala
event('click) { access =>
  for {
    _ <- access.transition(_.copy(loading = true))
    _ <- access.publish(MyEvent.SomethingHappened)

    value     <- access.valueOf(inputId)
    something <- myModel.readSomething(value)

    _ <- access.transition {
      case state: MyState.A =>
        MyState.B(value, something) 
    }
  } yield ()
}
```
 
Old API will be saved in `ApplicationContext` class. `ApplicationContext` will have `modern` property which will provide instance of `Context`. This allows to migrate applications smoothly, step by step.

If you have any ideas or objections, please, discuss it here.

**Comment by fomkin** [comment]
```scala
event('click) { access =>
  for {
    _ <- access.transition(_.copy(loading = true))
    _ <- access.publish(MyEvent.SomethingHappened)

    value     <- access.valueOf(inputId)
    something <- myMode.readSomething(value)

    _ <- access.transition {
      case state: MyState.A =>
        MyState.B(value, something) 
    }
  } yield ()
}
```
